### ISSUE TITLE
TA Comment - 撰寫使用者需求以及需求規格書

### ISSUE THREAD

**Issue by jo-ym** [Yi0409/BaseProject#2]
1. 開發同意書至少寫上雙方組名。
2. "開銷統計"此項功能, 在規格中的輸入"以往支出"是可以的(順便一提, 你們寫錯字把以寫成已了), 但在動作裏頭見不到這個資料是從哪裡而來了。

**Comment by D0580754** [comment]
[香蕉你的芭樂_需求規格書.docx](https://github.com/Yi0409/BaseProject/files/1625181/_.docx)

**Comment by D0580754** [comment]
[香蕉你的芭樂_騰訊把拔_系統開發同意書.pdf](https://github.com/Yi0409/BaseProject/files/1629326/_._.pdf)

**Comment by jo-ym** [comment]
以修改分數, 請上ilearn查看。
另外請記得都更新到docs裡頭。
